// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdifsnevmzpjizcmzyrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkaWZzbmV2bXpwaml6Y216eXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MTUwMDIsImV4cCI6MjA3OTk5MTAwMn0.eqjPRGqQU-ZsDoJ-8LHDwLFzGzwRb2VhBP2926aNMoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
